import React from 'react'
import Head from "next/head";
import Link from 'next/link';

export interface LayoutProps {
  children: React.ReactNode
}

export default function Layout({children}:LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-gray-800">
        <ul className="flex bg-gray-900 text-white px-3 py-5 rounded-md text-base font-medium">
          <li className="px-10">
            <Link href="/">
              <a>общая информация</a>
            </Link>
          </li>
          <li className="px-10">
            <Link href="/firstTask">
              <a>задача 1</a>
            </Link>
          </li>
          <li className="px-10">
            <Link href="/secondTask">
              <a>задача 2</a>
            </Link>
          </li>
        </ul>
      </header>
      <main>{children}</main>
    </>
  );
}
