import type { NextPage } from 'next'
import Head from 'next/head'
import {data} from '../data'


const Home: NextPage = () => {
  console.log(data)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='bg-pink-500'>Hello</h1>
      </main>

      <footer>
       
      </footer>
    </div>
  )
}

export default Home
